In [1]:
# Study Guide Code

import numpy as np
state = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]])
print('Initial state:')
print(state)
for dx in range(-1, 2):
    print('Shift by', dx)
    print(np.roll(state, shift=dx, axis=1))

Initial state:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shift by -1
[[ 2  3  4  1]
 [ 6  7  8  5]
 [10 11 12  9]
 [14 15 16 13]]
Shift by 0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shift by 1
[[ 4  1  2  3]
 [ 8  5  6  7]
 [12  9 10 11]
 [16 13 14 15]]


In [2]:
import matplotlib
matplotlib.use('TkAgg')
from pylab import *

n = 100 # size of space: n x n

global p # will make p intractive; see interactive_p function
p = 0.1 # probability of initially panicky individuals

def initialize():
    
    global config, nextconfig, density_lst # addded to global vars
    config = zeros([n, n])
    
    density_lst = [] # added a list for keeping track of density
    
    for x in range(n):
        for y in range(n):
            config[x, y] = 1 if random() < p else 0
    nextconfig = zeros([n, n])
    
def observe():
    global config, nextconfig, density_count # addded to global vars
    
    density_count = 0 
    
    for x in range(n): # looping to caclulate the density
        for y in range(n):
            density_count += config[(x) % n, (y) % n]
    
    cla()
    
    density_lst.append(density_count/(n*n)) # appending values
    
    subplot(1,2,1)
    imshow(config, vmin = 0, vmax = 1, cmap = cm.binary)
    
    subplot(1,2,2)
    plot(range(len(density_lst)), density_lst) # adding the time vs density plot
    

def update():
    global config, nextconfig
    for x in range(n):
        for y in range(n):
            count = 0
            for dx in [-1, 0, 1]:
                for dy in [-1, 0, 1]:
                    count += config[(x + dx) % n, (y + dy) % n]
#             nextconfig[x, y] = 1 if count >= 4 else 0 # old Panic CA config
            
            nextconfig[x ,y] = 1 if (count == 3 or count == 2) else 0 # new rules
            
    config, nextconfig = nextconfig, config
    
def interactive_p(val = p): # adding an interactive p parameter
    global p
    p = float(val)
    return val

import pycxsimulator
pycxsimulator.GUI(parameterSetters=[interactive_p]).start(func=[initialize, observe, update])

**Game of Life Rules**

* Any live cell with fewer than two live neighbors dies, as if by underpopulation.
* Any live cell with two or three live neighbors lives on to the next generation.
* Any live cell with more than three live neighbors dies, as if by overpopulation.
* Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.

**CA: 'p' parameter variations**

The phase transition for the Panic CA, i.e. the whole space getting filled with panic, happens around the intial density parameter of 0.4, around 0.5 the transition happens even a few seconds earlier. 